
name: "CI"
on: [push]

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MatteoH2O1999/setup-python@v1
        with: 
          python-version: 3.6 # version required for 2.2.28
      - name: "Test"
        run: |
            echo "testing"
            cd tests
            pip install -e .. 
            pip install -r requirements/py3.txt 
            python ./runtests.py
      - name: "Build"
        run: |
            echo "building"
            python setup.py sdist bdist_wheel
      - name: "Upload artifacts"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "artifacts"
          path: "dist/*"
